version: "3.9"


services:
  web:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
      - /etc/letsencrypt/live/REDACTED/fullchain.pem:/etc/letsencrypt/wildcard/REDACTED/fullchain.pem:ro
      - /etc/letsencrypt/live/REDACTED/privkey.pem:/etc/letsencrypt/wildcard/REDACTED/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend


  frontend:
    container_name: frontend
    image: REDACTED:frontend
    restart: unless-stopped


  backend:
    container_name: backend
    image: REDACTED:backend
    restart: unless-stopped
    ports:
      - "81:7000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380 


  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - "6380:6380"
    volumes:
      - ./redis.conf:/data/redis/redis.conf
    user: "${UID}:${GID}"
    command: ["redis-server", "/data/redis/redis.conf"]
